name: Simplecontainer client release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.22.x' ]
        platform: ['linux-amd64']
    steps:
      - uses: actions/checkout@v4
      - name: Install UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Display Go version
        run: go version
      - name: Test code
        run: go test
      - name: Build code
        run: |
          echo ${{ github.ref_name }} > version
          go build -o client-${{ matrix.platform }}
          upx -9 -k client-${{ matrix.platform }}
          git tag -d ${{ github.ref_name }}
          git push --delete origin ${{ github.ref_name }}
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Automated version tracking

          branch: main
          file_pattern: 'version'
          repository: .
          tagging_message: '${{ github.ref_name }}'

          commit_user_name: bot
          commit_user_email: bot@qdnqn.org
          commit_author: Author <actions@github.com>
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "client-${{ matrix.platform }}"
          body: "Automatically created - fill in accordingly"
          allowUpdates: true
          draft: true
          tag: ${{ github.ref_name }}

          


